# At some point, should probably change to generic (since using conda)
language: python

sudo: false

# TODO: various temp things in this PR for testing; will be undone
# before merge.
stages:
  - test
  - name: docs
    if: ((branch = master AND type != pull_request) OR (tag =~ ^v))
  - name: conda_dev_package
    if: (branch = packaging)

#    if: (branch = master AND type != pull_request)
#  - name: conda_package
#    if: tag =~ ^v


jobs:
  include:
    - &default
      stage: test
      python: "2.7"
#      before_install:
#        #########################
#        ##### install conda #####
#        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#        - bash miniconda.sh -b -p $HOME/miniconda
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        - hash -r
#        - conda config --set always_yes yes --set changeps1 no
#        - conda update -q conda
#        # Useful for debugging any issues with conda
#        - conda info -a
#        #########################
#        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
#        - source activate test-environment
#      install:
#        - conda install nose numpy matplotlib bokeh pandas scipy jupyter ipython param flake8 mock filelock cartopy xarray geopandas numpy shapely gdal libgdal datashader --quiet
#        - conda install -c conda-forge iris
#        - pip install coveralls
#        - pip install git+https://github.com/ioam/holoviews.git
#        - python setup.py install
#      script:
#        - nosetests --with-doctest --with-coverage --cover-package=geoviews
#        - flake8 --ignore=E,W . --exclude=./doc
#
#    - <<: *default
#      python: "3.6"
#      after_success: coveralls

    - <<: *default
      stage: docs
      python: "3.6"
      script:
        # TODO: can't remember why I did this twice
        - python -c "import geoviews as gv; gv.sample_data('notebooks/user_guide/sample-data')"
        - python -c "import geoviews as gv; gv.sample_data('doc/sample-data')"
        - python -c "import bokeh; bokeh.sampledata.download()"
        - conda install -c pyviz/label/dev -c conda-forge nbsite sphinx_ioam_theme
        - conda install -c nesii/label/dev-esmf -c conda-forge esmpy
        - pip install xesmf
        # TODO: should make this content available too rather than deleting it!
        - rm notebooks/*.ipynb
        - cd doc
        - nbsite_nbpagebuild.py ioam geoviews ../notebooks .
        # gallery notebooks depend on user guide assets
        - mkdir -p _build/html/user_guide
        - cp -r ../notebooks/user_guide/assets user_guide/
        - cp -r ../notebooks/user_guide/assets _build/html/user_guide/
        - cp -r ../notebooks/user_guide/sample-data _build/html/user_guide/
        - nbsite_gallery.py .. notebooks None '.' matplotlib bokeh None 
        - sphinx-build -b html . ./_build/html
        - nbsite_fix_links.py _build/html
        - nbsite_cleandisthtml.py ./_build/html take_a_chance
        - touch ./_build/html/.nojekyll
        - cd ..
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./doc/_build/html
          on:
            branch: master

    - &conda_default
      stage: conda_dev_package
      python: 3.6
      before_install:
        - pip install pyct && doit install_miniconda && rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda install -y -c pyviz/label/dev -c conda-forge pyct
        - doit ci_configure_conda
      install:
        - doit build_conda_package --channel conda-forge
      script: true
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN
#  
#    - <<: *conda_default
#      stage: conda_package
#      script:
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev
