{% set sdata = load_setup_py_data() %}

package:
  name: geoviews
  version: {{ sdata['version'] }}

source:
  path: ../..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python {{ sdata['python_requires'] }}  
    - geoviews-core =={{ sdata['version'] }}
    {% for dep in sdata['extras_require']['recommended'] %}
    - {{ dep }}
    {% endfor %}

test:
  imports:
    - geoviews

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
